# Docker Compose versión del formato del archivo
version: '3.8'

services:

  # Contenedor de la base de datos PostgreSQL
  db:
    image: postgres:16
    container_name: acceso_seguro_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Alejandro85
      POSTGRES_DB: acceso_seguro
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db-init:/docker-entrypoint-initdb.d
  # Verificamos que PostgreSQL esté listo antes de arrancar el backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  # Contenedor del backend Node.js
  backend:
    build: ./backend
    container_name: acceso_seguro_backend
    environment:
      DB_USER: postgres
      DB_HOST: db
      DB_NAME: acceso_seguro
      DB_PASSWORD: Alejandro85
      DB_PORT: 5432
      JWT_SECRET: acceso_seguro_clave_secreta_2026
    ports:
      - "3000:3000"
    depends_on:
      - db

  # Contenedor del frontend React
  frontend:
    build: .
    container_name: acceso_seguro_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

# Volumen para persistir los datos de PostgreSQL
volumes:
  postgres_data: